### PR TITLE
Clear out more async

### PR DESCRIPTION
**Pull request by davidrusu**
Changes:
- remove unused async
- remove RefCell in NetworkKnowledge
- remove Locks in SignatureAggregator and SectionKeyProvider

### CODE REVIEW

**Review by joshuef — APPROVED** [review]

**Comment by joshuef** [comment]
I've made https://github.com/maidsafe/safe_network/pull/1328 to try out a larger stack size just now

**Comment by b-zee** [comment]
An `Arc`ed value allocates on the heap. Good to note there is likely some stack increase after taking out `Arc`s.

**Comment by davidrusu** [comment]
@b-zee interesting :thinking: 

Some potential culprits:

LRUCache uses ArrayVec under the hood which looks like it is being stack-allocated:
https://docs.rs/arrayvec/latest/src/arrayvec/arrayvec.rs.html#42-46

We make use of it here: https://github.com/maidsafe/safe_network/pull/1325/files#diff-ec5edf7281e30ebd769a3b98e9bc61ff8a560acd21edc480f7882174bf66dc08R31-R34

I'll box it and see how things look

**Pull request merged**
