### PR TITLE
Tests improve faults

### PR DESCRIPTION
**Pull request by joshuef**

### CODE REVIEW

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try-

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try-

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try-

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Review by bochaco — APPROVED** [review]

**Pull request merged**
