### PR TITLE
feat(node): retry sending msg to peer cleaning all cached bad connections

### PR DESCRIPTION
**Pull request by bochaco**
- When sending a msg to a peer, if it fails with an existing cached connection, it will keep retrying till it either finds another cached connection which it succeeds with, or it cleans them all up from the cache creating a new connection to the peer as last attempt.
- Also this includes some minor improvements to Comm log msgs.
- Upgrading qp2p to v0.34.0.

### CODE REVIEW

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Review by joshuef — APPROVED** [review]

**Comment by bochaco** [comment]
bors try

**Comment by joshuef** [comment]
not sure why udeps has failed there 🤔 

bors r+

**Pull request merged**
