### PR TITLE
feat(client)!: include msg-id in sn_client::Error::CmdAckValidationTimeout

### PR DESCRIPTION
**Pull request by bochaco**
Running all sn-client tests multi-threaded in CI/Bors.

### CODE REVIEW

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try-

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Review by joshuef — APPROVED** [review]
bors r+

**Pull request merged**
