### PR TITLE
refactor(tests): removing query retrying loops and sleeps in sn-api/sn-client tests

### PR DESCRIPTION
**Pull request by bochaco**

### CODE REVIEW

**Review by joshuef — APPROVED** [review]

**Comment by bochaco** [comment]
It seems we better wait for some other other stability improvements on sn-node before merging this, as it keeps failing in CI. I've checked and it seems to be due to timeouts so hopefully is just that issue with sn-node locks delaying Ack responses.

**Comment by bochaco** [comment]
It seems the issue exposed by this PR is due to Elder timing out when waiting for Adult responses. I'm expecting PR #1753 to resolve it, so I'll be retrying to `bors` this after that one gets merged.

**Comment by joshuef** [comment]
Added do not merge for now just to make it clearer this is blocked

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
Removing `DO NOT MERGE` label since PR #1749 solved the issues that were exposed by this PR, and re-running bors now.

**Comment by bochaco** [comment]
Still some issue/s to review as `bors` failed in 4th attempt (3 passed in a row before failing).

**Comment by joshuef** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
@joshuef I decided to let `bors` merge this since I'm not able to get it to fail after a few tries, so if there is still any issues exposed by these changes it'll be better to have it in `main` branch as it'll be tested many more times by each of the incoming PR.

**Pull request merged**
