### PR TITLE
sn_node support for logrotate style logs (issue #938)

### PR DESCRIPTION
**Pull request by happybeing**

### CODE REVIEW

**Comment by happybeing** [comment]
Thanks @joshuef, will try rebase shortly.

I don't think the clippy error is mine as it is in `sn_cmd_test_utilities/src/lib.rs:50:30`. Should I fix it anyway?

**Comment by happybeing** [comment]
The rebase seems to have fixed the clippy warning so :crossed_fingers:

**Comment by oetyng** [comment]
Nice job @happybeing, looking forward to have this in.

The rebase though seems to have gone sideways, as all the commits from register->adults are included in this PR.

**Comment by happybeing** [comment]
Oh, and I thought I was almost there. This will have to wait until later or tomorrow now. I'm not sure what I did wrong. I'm not at my desktop but think I did:

```bash
git checkout main
git pull upstream main
git checkout node-logrotate
git rebase main
# fixed conflicts, committed changes then
git push
```

@oetyng Any idea where I went wrong?

**Comment by oetyng** [comment]
> @oetyng Any idea where I went wrong?

You know what, I'm not sure there's anything wrong now actually. The commit hashes are the same. This might be some bors trickery. Still unused to that.
This would be a classic sign otherwise of having committed same commits but with new hashes.

@josh, is this bors shenanigans we're seeing?

**Comment by bochaco** [comment]
> git rebase main
> fixed conflicts, committed changes then
> git push

perhaps you didn't do `rebase --continue` before `git push`

**Comment by happybeing** [comment]
I remember typing `git rebase --continue` so it's not that.

**Comment by joshuef** [comment]
(@joshuef @oetyng ;) ). 

I hit the `update branch` button here and that appears to hve straightened things out

**Review by joshuef — APPROVED** [review]

**Comment by joshuef** [comment]
So looking good locally. CI is having a bad time as we do some log searching there. 

I'll dive in here later on to add some commits to straighten that out. It's probably just adding a node flag or env var to disable compression and adding that to CI.

**Pull request merged**
