### PR TITLE
ci: reenable split test

### PR DESCRIPTION
**Pull request by joshuef**

### CODE REVIEW

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try -

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try-

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try-

**Comment by joshuef** [comment]
bors try

**Comment by oetyng** [comment]
bors try

**Comment by oetyng** [comment]
bors try

**Comment by oetyng** [comment]
bors try-

**Comment by oetyng** [comment]
bors try

**Comment by oetyng** [comment]
bors try

**Pull request closed without merging**
