### PR TITLE
feat(client): cap the number of concurrent chunks to be uploaded/retrieved for a file

### PR DESCRIPTION
**Pull request by bochaco**
Limiting the maximum number of chunks per file concurrently uploaded/retrieved to 5.

### CODE REVIEW

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Review by jacderida — APPROVED** [review]

**Review by jacderida — APPROVED** [review]

**Pull request merged**
