### PR TITLE
chore(ci): sn-client e2e tests on Ubuntu to run with 10secs timeout for cmds/queries

### PR DESCRIPTION
**Pull request by bochaco**
BREAKING CHANGE: using self_encryption v0.28.0 with max chunk size of 500kb.

### CODE REVIEW

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Review by joshuef — APPROVED** [review]

**Pull request merged**
