### PR TITLE
chore: .gitignore: remove duplicates entries, sort patterns inside of 'sections'

### PR DESCRIPTION
**Pull request by olegtaranenko**
Just minor sanitize of the .gitignore

### CODE REVIEW

**Review by joshuef — APPROVED** [review]
thanks @olegtaranenko ! 🙇

**Comment by joshuef** [comment]
Ah yeh, would you be so kind as to update the commit message to match https://www.conventionalcommits.org/en/v1.0.0/ style. We use this to version bump and generate the changelog.

eg: `chore: .gitignore: remove duplicates from, sort patterns insideo of 'sections'`

**Comment by olegtaranenko** [comment]
should I do it in the github or in git repository itself? BTW, I have switched off the pre-commit hook, because checking ends up with rejecting. 
I pushed new commit with chore: comment

**Comment by joshuef** [comment]
in the git repo itself.

what was failing in the pre commit hook?

**Comment by joshuef** [comment]
Sorry, @olegtaranenko can you rebase into just the one commit, also 🙇 it's still picking up the earlier commit msg as a fail

**Comment by olegtaranenko** [comment]
will create new PR

**Pull request closed without merging**
