### PR TITLE
ci: enable 40/100mb tests

### PR DESCRIPTION
**Pull request by joshuef**

### CODE REVIEW

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by oetyng** [comment]
bors try

**Comment by oetyng** [comment]
bors try

**Comment by oetyng** [comment]
bors try-

**Comment by oetyng** [comment]
bors try

**Review by oetyng — APPROVED** [review]

**Comment by oetyng** [comment]
bors try

**Comment by oetyng** [comment]
bors try-

**Comment by oetyng** [comment]
bors try

**Comment by oetyng** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Pull request merged**
