### PR TITLE
chore(logging): display binary prefix in logging code

### PR DESCRIPTION
**Pull request by Thierry61**
Display usual prefix binary representation instead of the name.

This is useful for dashboards analyzing log files.

### CODE REVIEW

**Comment by joshuef** [comment]
@Thierry61 Thanks for this. main change seems fine.

You'll need to update the following logs to be correct though: https://github.com/maidsafe/safe_network/pull/1044/files#diff-87e0a1c9b86a90561838367d66d6f23f01f6e2faf23488ad4dc270c2e58c8a13L66-L67

That's looking for a node's `name` as I understand it.

Also, we [follow conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) for commit messages to auto generate changelogs for release. So if you could reformat your message to follow that it would be great 🙇 (eg `chore: display binary prefix...`)

**Comment by Yoga07** [comment]
Hi @Thierry61 ,

This refactor changes printing from:
```
2022-02-28T10:32:54.755072Z DEBUG sn_launch_tool: Launching node #3...
Starting logging to directory: "C:\\Users\\yogesh\\.safe/node\\local-test-network\\sn-node-3"
Node PID: 23888, prefix: Prefix(), name: 0f4b97(00001111).., age: 96, connection info:
"127.0.0.1:49364"
"000000.." Node resource usage: Process { memory: 73457, virtual_memory: 4762624, cpu_usage: 4.166667, disk_usage: DiskUsage { total_written_bytes: 258504, written_bytes: 19690, total_read_bytes: 852716, read_bytes: 158 } }
```
to this:
```
2022-02-28T10:18:10.663954Z DEBUG sn_launch_tool: Launching node #14...
Starting logging to directory: "C:\\Users\\yogesh\\.safe/node\\local-test-network\\sn-node-14"
"(0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000)" Node resource usage: Process { memory: 79785, virtual_memory: 4741402, cpu_usage: 0.35047743, disk_usage: DiskUsage { total_written_bytes: 5550740, written_bytes: 5349776, total_read_bytes: 855853, read_bytes: 2620 } }
Node PID: 36684, prefix: Prefix(), name: 05f2b2(00000101).., age: 64, connection info:
"127.0.0.1:64759"
```
Is that verbose logging intended? Also FYI, printing the type `Prefix` prints the bits of the xorname prefix eg: `Prefix(01011..)` and strips the trailing zeros.

**Comment by Thierry61** [comment]
> if you could reformat your message to follow that it would be great

I modified it.

If it is still not OK, you should be able to do it yourself, as "Allow edits by maintainers" button is checked.

**Comment by Thierry61** [comment]
> printing the type `Prefix` prints the bits of the xorname prefix and strips the trailing zeros

No, printing the type Prefix doesn’t do this. Previously the name of the prefix (`ctx.prefix().await.name()`) was printed which does this, but is not the prefix (`ctx.prefix().await`)

For whatever reason when this function is called in your test the prefix has 256 bits, which is not a normal condition but is the reality. This reality shouldn’t be hidden by printing the prefix name instead of the usual prefix representation.

Or, you can hide the reality in this very specific condition, but this shouldn’t impact usual prefix representation in normal conditions (and I let you code this specific case!).

**Comment by Thierry61** [comment]
> That's looking for a node's `name` as I understand it.

I don’t understand, I just replaced printing the name of the prefix by printing the prefix.

Please note that I only tested the code with an empty prefix, my network was too small to trigger splits.

**Comment by joshuef** [comment]
> I don’t understand, I just replaced printing the name of the prefix by printing the prefix.

Ah sorry, I appear to have grabbed the wrong link there. 🤦 

https://github.com/maidsafe/safe_network/pull/1044/files#diff-87e0a1c9b86a90561838367d66d6f23f01f6e2faf23488ad4dc270c2e58c8a13L66-L67

Here the `prefix` var is used expecting it to be `name`. :| Which yes, We need the variable naming to be updated here as that's obviously wrong.

But basically, updating the `prefix` var to be `prefix` and not `name` will mess with the pending logs. So we just need a `name` var created and used in those logs below too.
----

> I modified it.

It's still missing the scope. (https://www.conventionalcommits.org/en/v1.0.0/#summary)

If you can get that in if there are more changes that'd be great. 
----

>This reality shouldn’t be hidden by printing the prefix name instead of the usual prefix representation.

Yeh that's fair enough 👍 

@Thierry61 Just for clarity, what are you looking to achieve here? What is missing from a log such as `prefix: Prefix(101)` eg?

**Comment by Thierry61** [comment]
> Just for clarity, what are you looking to achieve here?

As mentioned in [this topic](https://safenetforum.org/t/update-24-february-2022/36669/14?u=tfa) I didn’t find a proper way to get current node prefix in the logs:

- “Known prefix after update:” is generated in a loop which means several of them can be listed
- “Section updated: prefix:” is reserved for elders and unavailable for adults
- prefix at the end of “Node resource usage:” isn’t in the right format (000000… instead of ())

This PR is about the third point. I am not sure this is the best way to get the prefix for the dashboard, but anyway the prefix should be displayed using its usual binary representation and not its name.

But if you have a better way to get the prefix of current node I am interested.

**Comment by Thierry61** [comment]
> But basically, updating the `prefix` var to be `prefix` and not `name` will mess with the pending logs

I don't use print_resources_usage flag, so what can be done is to move definition of prefix variable and duplicate it in 2 versions:
- original one (`let prefix: &str = &format!("{}", ctx.prefix().await.name());`) in print_resources_usage branch
- new one in (`let prefix: &str = &format!("({:b})", ctx.prefix().await);`) in else branch

This way your logs (or more exactly your stdout) are not messed with.

But you are aware that prefix name doesn't represent much.

**Comment by Yoga07** [comment]
Hey @Thierry61 ,

By type `Prefix` I meant the struct itself and not the variable `prefix`. So for clarification:
```
println!("{:?}", format!("{:?}", ctx.prefix().await));
prints: "Prefix(0)" 

println!("{:?}", format!("{:?}", ctx.prefix().await.name()));
prints: "000000(00000000).."
```

>This PR is about the third point. I am not sure this is the best way to get the prefix for the dashboard, but anyway the prefix should be displayed using its usual binary representation and not its name.
>But if you have a better way to get the prefix of current node I am interested.

Do the above types of formatting not suffice your requirements? It should be easy to get the only prefix out of `Prefix(xxx)` yes? (i.e the trailing zeros are removed already)

**Comment by Thierry61** [comment]
> Do the above types of formatting not suffice your requirements?

First formatting (`Prefix(0)`) would be OK.

But second one (`000000(00000000)..`) obviously not because `00000000` is different from `0` (prefix depth is not right).

**Comment by Thierry61** [comment]
I committed modification suggested by @Yoga07.

Another remark is the unusual trace statement that doesn’t adhere to the principle of least surprise (prefix is the first argument but appears last in the output).

https://github.com/maidsafe/safe_network/blob/507aa3cf0f23ab149c5865e1d9d0c11ddde1c39e/sn/src/node/logging/mod.rs#L71-L75

Why not a standard trace statement with format string as first argument ?

**Comment by Yoga07** [comment]
> Another remark is the unusual trace statement that doesn’t adhere to the principle of least surprise (prefix is the first argument but appears last in the output).
> 
> https://github.com/maidsafe/safe_network/blob/507aa3cf0f23ab149c5865e1d9d0c11ddde1c39e/sn/src/node/logging/mod.rs#L71-L75
> 
> Why not a standard trace statement with format string as first argument ?

Absolutely. I've opened https://github.com/maidsafe/safe_network/pull/1062 including this change just to have the commits 
 a bit neater. 
Thanks, @Thierry61 :)

**Pull request closed without merging**
