### PR TITLE
chore: minor logging improvements to help debug msgs arriving/processing on client and nodes

### PR DESCRIPTION
**Pull request by bochaco**

### CODE REVIEW

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Review by joshuef — APPROVED** [review]

**Pull request merged**
