### PR TITLE
ci: assert we have expected node count during tests

### PR DESCRIPTION
**Pull request by joshuef**

### CODE REVIEW

**Review by oetyng — DISMISSED** [review]

**Comment by oetyng** [comment]
bors try

**Comment by oetyng** [comment]
bors try-

**Comment by oetyng** [comment]
bors try

**Comment by oetyng** [comment]
bord r+

**Comment by oetyng** [comment]
bors try

**Comment by oetyng** [comment]
bors try

**Comment by joshuef** [comment]
bors try

**Pull request closed without merging**
