### PR TITLE
refactor(comms): simplify peer_session

### PR DESCRIPTION
**Pull request by oetyng**
- Removes some unnecessary spawning and channel faff, since we're already on a new thread.

### CODE REVIEW

**Comment by oetyng** [comment]
bors try

**Review by b-zee — APPROVED** [review]

**Comment by oetyng** [comment]
bors try

**Comment by oetyng** [comment]
bors try

**Comment by oetyng** [comment]
bors try

**Comment by oetyng** [comment]
bors try

**Pull request merged**
