### PR TITLE
feat(ci): verify members in network knowledge are the expected

### PR DESCRIPTION
**Pull request by bochaco**
- Additional checks added to all_nodes_joined.sh script to be able to detect nodes in the network knowledge which are not those that effectively joined the network.
- Also some minor improvements to sn_client log msgs.

Example output when there is a mismatch of members and joined nodes:
```
Checking nodes log files to verify all nodes have joined. Logs path: ~/.safe/node/local-test-network
Number of nodes: 15
All nodes have joined. Nodes IPs:
127.0.0.1:57739
127.0.0.1:57751
127.0.0.1:57745
127.0.0.1:57740
127.0.0.1:57747
127.0.0.1:57748
127.0.0.1:57749
127.0.0.1:57754
127.0.0.1:57744
127.0.0.1:57741
127.0.0.1:57742
127.0.0.1:57743
127.0.0.1:57752
127.0.0.1:57750
127.0.0.1:57753

Checking if nodes in network knowledge match the list of nodes IPs...
Node 127.0.0.1:57750 is a valid member
Node 127.0.0.1:57746 in network knowledge was not found in the list of nodes IPs
Node 127.0.0.1:57753 is a valid member
Node 127.0.0.1:57741 is a valid member
Node 127.0.0.1:57743 is a valid member
Node 127.0.0.1:57752 is a valid member
Node 127.0.0.1:57739 is a valid member
Node 127.0.0.1:57748 is a valid member
Node 127.0.0.1:57751 is a valid member
Node 127.0.0.1:57747 is a valid member
Node 127.0.0.1:57744 is a valid member
Node 127.0.0.1:57749 is a valid member
Node 127.0.0.1:57740 is a valid member
Node 127.0.0.1:57745 is a valid member
Node 127.0.0.1:57742 is a valid member

At least one member in the network knowledge was found invalid
```

### CODE REVIEW

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Comment by bochaco** [comment]
bors try

**Review by joshuef — APPROVED** [review]

**Pull request merged**
